### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by szaghi** [francescosalvadore/openpde#3]
Dear @francescosalvadore 

I think it is important to provide license information. How your **openpde** should be _distributed_?

I the [pull request](https://github.com/francescosalvadore/openpde/pull/2) that I have just made (I hope you will accept my contribution even if you have not yet replayed to my first issue :smile: ) I have added _contributing_ guidelines supposing that your **openpde** is opened to contributions...

**Comment by francescosalvadore** [comment]
Agreed!

**Comment by szaghi** [comment]
I added a _complicated licensing system_ that means _do whatever you want with this_... it is the most permissive licensing system I have found on the web catching both FOSS-irreducible users and who want more-commercial-friendly license.

I close this issue, reopen it if my licensing system is wrong for you.
