### ISSUE TITLE
Why class(mesh) pointer member rather an allocatable?

### ISSUE THREAD

**Issue by szaghi** [francescosalvadore/openpde#6]
Hi @francescosalvadore 

why for the _mesh_ member of the field you have designed a `class(mesh), pointer :: m` instead of `class(mesh), allocatable`, i.e. see [this](https://github.com/francescosalvadore/openpde/blob/master/src/lib/opendiff.f90#L34)?

I have to admit that my _confidence_ with pointers is poor, so I cannot understand why a _simpler_ `allocatable` is not enough, thus we need a pointer.

**Comment by francescosalvadore** [comment]
Hi @szaghi 
the same mesh is expected to be used by many fields so we do not embed the mesh in the field storage. Am I right?
The design in the very early stage, I do not know if the current choices make sense!

**Comment by szaghi** [comment]
Hi @francescosalvadore 

Wonderful!

I was not going so far... you are right! Pointer is better!
