### ISSUE TITLE
Convert "associate_mesh/field..." subroutine to function 

### ISSUE THREAD

**Issue by szaghi** [francescosalvadore/openpde#7]
To mimic C++ down casting, it is convenient to transform auxiliary subroutine like [this](https://github.com/francescosalvadore/openpde/blob/master/src/lib/openpde_field/openpde_field_FD_1D.f90#L34) to function returning the correct pointer.

**Comment by francescosalvadore** [comment]
Agree. Something like
mesh_cur => associate_mesh_FD_1D(mesh)
and with optional error message e.g.
mesh_cur => associate_mesh_FD_1D(mesh, "Error casting mesh to mesh_FD_1D")
would be good IMO.

**Comment by szaghi** [comment]
@francescosalvadore LGTM!

Can I go to implement this change or you are doing something **big**?

**Comment by francescosalvadore** [comment]
working on new files, no problem :)

**Comment by szaghi** [comment]
@francescosalvadore 

Done in the last commit [pushed](https://github.com/francescosalvadore/openpde/commit/9b84077b8f63a40f98fb29801edfb23fe80bc345) to master branch.

Note that I have adopted the following API:

``` fortran
mesh_cur => associate_mesh_FD_1D(mesh_input=mymesh, emsg='calling proc blabla')
```

where `emsg` is an optional _auxiliary_ message: even if not passed, the associate function print a meaningful error message to stderr before quitting. Passing also `emsg` results into a message like

``` bash
error: cast mesh to mesh_FD_1D
calling procedure blabla
```

I hope you like, but the messages can be easily changed.
