### ISSUE TITLE
source vs mold

### ISSUE THREAD

**Issue by francescosalvadore** [francescosalvadore/openpde#8]
Probably instead of allocate(a,source=b) we usually need F2008 allocate(a,mold=b).

**Comment by szaghi** [comment]
@francescosalvadore 

Ok, but I am not aware about what implies `mold` instead of `source`...

**Comment by szaghi** [comment]
@francescosalvadore 

I found an interesting `mold` explanation:

> The MOLD= specifier works almost in the same way as SOURCE=.  Like SOURCE=, MOLD= causes the object to be allocated to have the same type and type parameters as the source_expr specified in the MOLD= specifier.  Similarly, if you don't specify the bounds for an array in the ALLOCATE statement, the bounds of source_expr in the MOLD= specifier determine the bounds of the array. Unlike SOURCE=, MOLD= does not copy the value of source_expr to the variable to be allocated. Because no copying takes place, if source_expr in MOLD= is a variable, its value need not be defined.

Nice, I can now go to change all source allocations... can I?

**Comment by szaghi** [comment]
@francescosalvadore 

Done :smile: 

It happens that only the `interpolator_euler_explict` had a source allocation...

For the future I will remember to use `mold` instead of `source` when copy is not necessary.
